// Interface to communicate with Go objects
//
// This file will eventually be automatically generated from the Go code
// @see EventType automated generation
// Re-export types autogenerated by Go
export { IntentType as EventsCodes } from "../rx/intenttype_abi";
//# sourceMappingURL=datacell-abi.js.map