// Code generated by polgen; DO NOT EDIT.
//go:generate go run ./polgen

package iam

var policyActionTable = []struct {
	Name string
	Code Action
}{
	{"admin/%", 0o1000},
	{"admin/create_user", 0o1001},
	{"admin/update_license", 0o1002},
	{"audit/%", 0o2000},
	{"audit/assign", 0o2001},
	{"audit/schedule", 0o2002},
	{"datasource/%", 0o3000},
	{"datasource/connect", 0o3001},
	{"datasource/write", 0o3002},
	{"mdt/%", 0o4000},
	{"mdt/view_field", 0o4001},
	{"playbook/%", 0o5000},
	{"playbook/assign", 0o5001},
	{"playbook/create", 0o5002},
	{"playbook/escalate", 0o5003},
	{"playbook/open", 0o5004},
	{"playbook/resolve", 0o5005},
	{"policy/%", 0o6000},
	{"policy/create", 0o6001},
	{"policy/open", 0o6002},
	{"schedule/%", 0o7000},
	{"schedule/remove", 0o7001},
	{"schedule/start", 0o7002},
	{"schedule/stop", 0o7003},
	{"search/%", 0o10000},
	{"search/notebook", 0o10001},
	{"search/user", 0o10002},
	{"snapshot/%", 0o11000},
	{"snapshot/erase", 0o11001},
}

const (
	PermAdminCreateUser    = 0o1001
	PermAdminUpdateLicense = 0o1002
	PermAuditAssign        = 0o2001
	PermAuditSchedule      = 0o2002
	PermDatasourceConnect  = 0o3001
	PermDatasourceWrite    = 0o3002
	PermMdtViewField       = 0o4001
	PermPlaybookAssign     = 0o5001
	PermPlaybookCreate     = 0o5002
	PermPlaybookEscalate   = 0o5003
	PermPlaybookOpen       = 0o5004
	PermPlaybookResolve    = 0o5005
	PermPolicyCreate       = 0o6001
	PermPolicyOpen         = 0o6002
	PermScheduleRemove     = 0o7001
	PermScheduleStart      = 0o7002
	PermScheduleStop       = 0o7003
	PermSearchNotebook     = 0o10001
	PermSearchUser         = 0o10002
	PermSnapshotErase      = 0o11001

	noSuchAction = 0o100000
)
