// Code generated by the constrainer; DO NOT EDIT.
//go:build linux

package mdt

import (
	"trout.software/kraken/webapp/internal/sqlite"
)

func (r lpath) Getrecord(cs sqlite.Constraints) (v []byte) {
	match := 0
	for _, c := range cs {
		if c.Column == "rc" {
			if c.Operation == sqlite.ConstraintEQ {
				v = c.ValueBytes()
				match++
			} else {
				panic("Value getter with non-constrained values")
			}
		}
	}

	if match != 1 {
		panic("field should have been filtered")
	}

	return v
}

func (r lpath) Getpath(cs sqlite.Constraints) (v string) {
	match := 0
	for _, c := range cs {
		if c.Column == "path" {
			if c.Operation == sqlite.ConstraintEQ {
				v = c.ValueString()
				match++
			} else {
				panic("Value getter with non-constrained values")
			}
		}
	}

	if match != 1 {
		panic("field should have been filtered")
	}

	return v
}
