// Code generated by "rxabi -type IntentType"; DO NOT EDIT.
// This file should be tracked by the version manager
export var IntentType;
(function (IntentType) {
    IntentType[IntentType["NoIntent"] = 0] = "NoIntent";
    IntentType[IntentType["Click"] = 1] = "Click";
    IntentType[IntentType["DoubleClick"] = 2] = "DoubleClick";
    IntentType[IntentType["DragStart"] = 3] = "DragStart";
    IntentType[IntentType["DragOver"] = 4] = "DragOver";
    IntentType[IntentType["DragEnd"] = 5] = "DragEnd";
    IntentType[IntentType["Drop"] = 6] = "Drop";
    IntentType[IntentType["EscPress"] = 7] = "EscPress";
    IntentType[IntentType["Scroll"] = 8] = "Scroll";
    IntentType[IntentType["Filter"] = 9] = "Filter";
    IntentType[IntentType["Change"] = 10] = "Change";
    IntentType[IntentType["Blur"] = 11] = "Blur";
    IntentType[IntentType["ChangeView"] = 12] = "ChangeView";
    IntentType[IntentType["CellIDChange"] = 13] = "CellIDChange";
    IntentType[IntentType["ShowDebugMenu"] = 14] = "ShowDebugMenu";
    IntentType[IntentType["Seppuku"] = 15] = "Seppuku";
})(IntentType || (IntentType = {}));
//# sourceMappingURL=intenttype_abi.js.map