// Code generated by "rxabi -type OpType"; DO NOT EDIT.
// This file should be tracked by the version manager

export enum OpType {
	OpTerm= 0,
	OpCreateElement= 1,
	OpSetClass= 2,
	OpSetID= 3,
	OpSetAttr= 4,
	OpAddText= 5,
	OpReuse= 6,
	OpReID= 7,
	OpNext= 8,
}