// Code generated by "rxabi -type OpType"; DO NOT EDIT.
// This file should be tracked by the version manager
export var OpType;
(function (OpType) {
    OpType[OpType["OpTerm"] = 0] = "OpTerm";
    OpType[OpType["OpCreateElement"] = 1] = "OpCreateElement";
    OpType[OpType["OpSetClass"] = 2] = "OpSetClass";
    OpType[OpType["OpSetID"] = 3] = "OpSetID";
    OpType[OpType["OpSetAttr"] = 4] = "OpSetAttr";
    OpType[OpType["OpAddText"] = 5] = "OpAddText";
    OpType[OpType["OpReuse"] = 6] = "OpReuse";
    OpType[OpType["OpReID"] = 7] = "OpReID";
    OpType[OpType["OpNext"] = 8] = "OpNext";
})(OpType || (OpType = {}));
//# sourceMappingURL=optype_abi.js.map